# Generated by Django 6.0.3 on 2026-03-25 11:10

import django.db.models.deletion
import django.utils.timezone
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('electrician', 'Electrician'), ('plumber', 'Plumber'), ('carpenter', 'Carpenter'), ('hvac', 'HVAC'), ('maintenance', 'Maintenance'), ('inspection', 'Inspection'), ('cleaning', 'Cleaning'), ('installation', 'Installation'), ('repair', 'Repair'), ('other', 'Other')], default='other', max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('due_date', models.DateField(default=django.utils.timezone.localdate)),
                ('estimated_hours', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('location', models.CharField(blank=True, max_length=300)),
                ('location_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('location_lon', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('employee_notes', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_date', '-priority', 'created_at'],
            },
        ),
    ]
