# Generated by Django 6.0.3 on 2026-03-25 11:10

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeLog',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('work_date', models.DateField(db_index=True)),
                ('clock_in', models.DateTimeField()),
                ('clock_in_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('clock_in_lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('clock_in_address', models.TextField(blank=True)),
                ('clock_in_notes', models.TextField(blank=True)),
                ('clock_in_photo', models.ImageField(blank=True, null=True, upload_to='time_logs/photos/')),
                ('clock_out', models.DateTimeField(blank=True, null=True)),
                ('clock_out_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('clock_out_lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('clock_out_address', models.TextField(blank=True)),
                ('clock_out_notes', models.TextField(blank=True)),
                ('clock_out_photo', models.ImageField(blank=True, null=True, upload_to='time_logs/photos/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_logs', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Break',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('break_start', models.DateTimeField()),
                ('break_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('time_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='time_tracking.timelog')),
            ],
        ),
        migrations.AddIndex(
            model_name='timelog',
            index=models.Index(fields=['employee', 'work_date'], name='time_tracki_employe_d88427_idx'),
        ),
    ]
