export const routes = {
  login: "/login",
  dashboard: "/",
  locations: "/locations",
  time: "/time",
  tasks: "/tasks",
  leaves: "/leaves",
  payroll: "/payroll",
  scheduling: "/scheduling",
  employees: "/employees",
  reports: "/reports",
  settings: "/settings",
  get_started: "/get-started",
  live_locations: "/live-locations",
  settings_people: "/settings/people",
  settings_timetracking: "/settings/time-tracking",
  settings_schedules: "/settings/schedules",
  settings_holidays: "/settings/holidays",
  settings_locations: "/settings/locations",
  settings_projects: "/settings/projects",
  settings_organization: "/settings/organization",
  settings_integrations: "/settings/integrations",
  onboarding: "/onboarding",
}

